{{- range $name, $svc := .Values.services -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docker-compose.fullname" $ }}-env-{{ $name }}
  labels:
    {{- include "docker-compose.labels" $ | nindent 4 }}
    docker-compose/service: {{ $name }}
type: Opaque
data:
{{- range $key, $val := .environment -}}
  {{- if contains "=" $val }}
  {{- $parts := splitn "=" 2 $val }}
  {{ $parts._0 }}: {{ $parts._1 | b64enc | quote }}
  {{- else }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
{{ end }}
