{{- range $name, $svc := .Values.services -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "docker-compose.serviceName" $name }}
  labels:
    {{- include "docker-compose.labels" $ | nindent 4 }}
    docker-compose/service: {{ $name }}
spec:
  type: ClusterIP
  ports:
    {{- range $idx, $port := $svc.ports }}
    - port: {{ (split ":" $port)._0 }}
      targetPort: port-{{ $idx }}
      protocol: TCP
      name: port-{{ $idx }}
    {{- end }}
    {{- range $idx, $port := $svc.expose }}
    - port: {{ $port }}
      targetPort: expose-{{ $idx }}
      protocol: TCP
      name: expose-{{ $idx }}
    {{- end }}
  selector:
    {{- include "docker-compose.selectorLabels" $ | nindent 4 }}
    docker-compose/service: {{ $name }}
{{ end -}}
