apiVersion: v2
name: huaweisolarfusion-exporter
description: Scrape and export huaweisolarfustion metrics
type: application
version: 0.1.1
appVersion: 1.0.1
maintainers:
  - name: NoUseFreak
    email: dries@stenic.io
    url: https://stenic.io
