apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clusterfan.fullname" . }}-master
  labels:
    {{- include "clusterfan.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "clusterfan.selectorLabels" . | nindent 6 }}
      app: {{ include "clusterfan.fullname" . }}-master
  template:
    metadata:
      labels:
        {{- include "clusterfan.selectorLabels" . | nindent 8 }}
        app: {{ include "clusterfan.fullname" . }}-master
    spec:
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.pwm.hostname }}
      containers:
      - name: {{ .Chart.Name }}-master
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: Always
        securityContext:
          capabilities:
            add: ["SYS_ADMIN"]
          privileged: true
          allowPrivilegeEscalation: true
        env:
        - name: CLUSTERFAN_ISMASTER
          value: "true"
        - name: CLUSTERFAN_SPEEDMAP
          value: '{"40":100,"30":50,"20":0}'
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 20Mi
            cpu: 50m
          requests:
            cpu: 30m
            memory: 20Mi
        volumeMounts:
        - mountPath: /sys
          name: sys-tree
      volumes:
      - name: sys-tree
        hostPath:
          path: /sys