apiVersion: v1
kind: Service
metadata:
  name: {{ include "clusterfan.fullname" . }}-master
  labels:
    {{- include "clusterfan.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "clusterfan.selectorLabels" . | nindent 4 }}
    app: {{ include "clusterfan.fullname" . }}-master
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080